CREATE TABLE "order"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_id BIGINT,
    date      date,
    status    INT                                     NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_SELLER FOREIGN KEY (seller_id) REFERENCES seller (id);